#!/bin/bash

if [ -f "/usr/local/cpanel/cpanel_hfn" ]; then
oldversion=$( cat /usr/local/cpanel/cpanel_hfn )
newversion=$( curl -s https://raw.githubusercontent.com/tactu2023/cpanel-nulled/main/version )

if [ "$newversion" -gt "$oldversion" ]; then
echo Your license need update [ version:$newversion ]
rm -f /opt/tactu_cpanel
rm -f  /usr/local/cpanel/cpanel_hfn
curl -o /opt/tactu_cpanel -s -L https://raw.githubusercontent.com/tactu2023/cPanel-nulled/main/tactu_cpanel.x
chmod +x /opt/tactu_cpanel
echo "17" | tee -a /usr/local/cpanel/cpanel_hfn
rm -f /usr/bin/tactu_cpanel
curl -o /usr/bin/tactu_cpanel -s -L https://raw.githubusercontent.com/tactu2023/cPanel-nulled/main/tactu_cpanel
chmod +x /usr/bin/tactu_cpanel
fi

currentVersion=$(cat /usr/local/cpanel/cpanel_hfn)
if [ "$newversion" = "$currentVersion" ]; then
echo "You are now using the latest version [ $currentVersion ]"
fi
fi
