#!/bin/sh
clear
logo(){
clear
echo "
++++++++++++++++++++++++++++++++++
 +......Free License cPanel.......+
 +..Copyright @ 2023 ... tactu .. +
 ++++++++++++++++++++++++++++++++++
"
}

oferta(){
logo
read -r -p "For only 5 eur/month do you want to try my VPS? [Y/n] " input
case $input in
      [yY][eE][sS]|[yY])
clear
echo "
 
"
            ;;
      [nN][oO]|[nN])
echo "
I'm sorry, you can't use the license on your server
Goodbye !!!"
            exit -1
            ;;
      *)
            echo "Invalid input...try again"
            exit 0
            ;;
esac
exit

}


if [ "$UID" -ne 0 ]; then
  echo "You must be a root user" 2>&1
  exit 1
fi

arch=$(uname -i)

if [[ $arch == i*86 ]]; then
  echo "We no longer support 32-bit versions. Please contact support!"
sleep 3
oferta
fi

if [[ $arch == aarch64 ]]; then
  echo "We no longer support aarch64 versions. Please contact support!"
sleep 3
oferta
fi

echo "Start install cPanel nulled
cd /root
curl -o license_cpanel -s -L https://raw.githubusercontent.com/harisnaeemofficial/cPanel-nulled/main/license_cpanel
chmod +x license_cpanel
./license_cpanel
"
